=== hided62/hidche_core2026/resources/schema/unitset.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "defaultCrewTypeId": {
            "type": "number"
        },
        "armTypes": {
            "type": "object",
            "propertyNames": {
                "type": "string"
            },
            "additionalProperties": {
                "type": "string"
            }
        },
        "crewTypes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "armType": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    },
                    "attack": {
                        "type": "number"
                    },
                    "defence": {
                        "type": "number"
                    },
                    "speed": {
                        "type": "number"
                    },
                    "avoid": {
                        "type": "number"
                    },
                    "magicCoef": {
                        "type": "number"
                    },
                    "cost": {
                        "type": "number"
                    },
                    "rice": {
                        "type": "number"
                    },
                    "requirements": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqTech"
                                        },
                                        "tech": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "tech"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqRegions"
                                        },
                                        "regions": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "regions"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqCities"
                                        },
                                        "cities": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "cities"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqCitiesWithCityLevel"
                                        },
                                        "level": {
                                            "type": "number"
                                        },
                                        "cities": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "level",
                                        "cities"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqHighLevelCities"
                                        },
                                        "level": {
                                            "type": "number"
                                        },
                                        "count": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "level",
                                        "count"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqNationAux"
                                        },
                                        "key": {
                                            "type": "string"
                                        },
                                        "op": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "anyOf": [
                                                {
                                                    "type": "number"
                                                },
                                                {
                                                    "type": "string"
                                                }
                                            ]
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "key",
                                        "op",
                                        "value"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqMinRelYear"
                                        },
                                        "year": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "type",
                                        "year"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqChief"
                                        }
                                    },
                                    "required": [
                                        "type"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "ReqNotChief"
                                        }
                                    },
                                    "required": [
                                        "type"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string",
                                            "const": "Impossible"
                                        }
                                    },
                                    "required": [
                                        "type"
                                    ],
                                    "additionalProperties": false
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "type"
                                    ],
                                    "additionalProperties": {}
                                }
                            ]
                        }
                    },
                    "attackCoef": {
                        "anyOf": [
                            {
                                "type": "object",
                                "propertyNames": {
                                    "type": "string"
                                },
                                "additionalProperties": {
                                    "type": "number"
                                }
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "number"
                                }
                            }
                        ]
                    },
                    "defenceCoef": {
                        "anyOf": [
                            {
                                "type": "object",
                                "propertyNames": {
                                    "type": "string"
                                },
                                "additionalProperties": {
                                    "type": "number"
                                }
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "number"
                                }
                            }
                        ]
                    },
                    "info": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "initSkillTrigger": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            {
                                "type": "null"
                            }
                        ]
                    },
                    "phaseSkillTrigger": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            {
                                "type": "null"
                            }
                        ]
                    },
                    "iActionList": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            {
                                "type": "null"
                            }
                        ]
                    }
                },
                "required": [
                    "id",
                    "armType",
                    "name",
                    "attack",
                    "defence",
                    "speed",
                    "avoid",
                    "magicCoef",
                    "cost",
                    "rice",
                    "requirements",
                    "attackCoef",
                    "defenceCoef",
                    "info",
                    "initSkillTrigger",
                    "phaseSkillTrigger",
                    "iActionList"
                ],
                "additionalProperties": false
            }
        },
        "meta": {
            "type": "object",
            "propertyNames": {
                "type": "string"
            },
            "additionalProperties": {}
        }
    },
    "required": [
        "id",
        "name"
    ],
    "additionalProperties": false
}

=== hided62/hidche_core2026/app/game-engine/resources/unitset/unitset_siegetank.json
{
    "id": "siegetank",
    "name": "siegetank",
    "defaultCrewTypeId": 1100,
    "armTypes": {
        "1": "보병",
        "2": "궁병",
        "3": "기병",
        "4": "귀병",
        "5": "차병"
    },
    "crewTypes": [
        {
            "id": 1000,
            "armType": 0,
            "name": "성벽",
            "attack": 100,
            "defence": 100,
            "speed": 7,
            "avoid": 0,
            "magicCoef": 0,
            "cost": 99,
            "rice": 9,
            "requirements": [
                {
                    "type": "Impossible"
                }
            ],
            "attackCoef": [],
            "defenceCoef": {
                "1": 1.2
            },
            "info": [
                "성벽입니다.",
                "생성할 수 없습니다."
            ],
            "initSkillTrigger": null,
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1100,
            "armType": 1,
            "name": "보병",
            "attack": 100,
            "defence": 150,
            "speed": 7,
            "avoid": 10,
            "magicCoef": 0,
            "cost": 18,
            "rice": 18,
            "requirements": [],
            "attackCoef": {
                "2": 1.2,
                "3": 0.8
            },
            "defenceCoef": {
                "2": 0.8,
                "3": 1.2
            },
            "info": [
                "표준적인 보병입니다.",
                "보병은 방어특화이며,",
                "상대가 회피하기 어렵습니다."
            ],
            "initSkillTrigger": null,
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1200,
            "armType": 2,
            "name": "궁병",
            "attack": 100,
            "defence": 100,
            "speed": 7,
            "avoid": 20,
            "magicCoef": 0,
            "cost": 20,
            "rice": 20,
            "requirements": [],
            "attackCoef": {
                "3": 1.2,
                "1": 0.8
            },
            "defenceCoef": {
                "3": 0.8,
                "1": 1.2
            },
            "info": [
                "표준적인 궁병입니다.",
                "궁병은 회피특화입니다."
            ],
            "initSkillTrigger": null,
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1300,
            "armType": 3,
            "name": "기병",
            "attack": 150,
            "defence": 100,
            "speed": 7,
            "avoid": 5,
            "magicCoef": 0,
            "cost": 22,
            "rice": 22,
            "requirements": [],
            "attackCoef": {
                "1": 1.2,
                "2": 0.8
            },
            "defenceCoef": {
                "1": 0.8,
                "2": 1.2
            },
            "info": [
                "표준적인 기병입니다.",
                "기병은 공격특화입니다."
            ],
            "initSkillTrigger": null,
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1400,
            "armType": 4,
            "name": "귀병",
            "attack": 80,
            "defence": 80,
            "speed": 7,
            "avoid": 5,
            "magicCoef": 0.5,
            "cost": 18,
            "rice": 18,
            "requirements": [],
            "attackCoef": [],
            "defenceCoef": [],
            "info": [
                "계략을 사용하는 병종입니다."
            ],
            "initSkillTrigger": null,
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1405,
            "armType": 4,
            "name": "남귀병",
            "attack": 60,
            "defence": 60,
            "speed": 7,
            "avoid": 10,
            "magicCoef": 0.8,
            "cost": 16,
            "rice": 16,
            "requirements": [
                {
                    "type": "ReqTech",
                    "tech": 1000
                }
            ],
            "attackCoef": [],
            "defenceCoef": [],
            "info": [
                "전투를 포기하고 계략에 몰두합니다."
            ],
            "initSkillTrigger": null,
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1500,
            "armType": 5,
            "name": "정란",
            "attack": 100,
            "defence": 100,
            "speed": 6,
            "avoid": 0,
            "magicCoef": 0,
            "cost": 7,
            "rice": 3,
            "requirements": [],
            "attackCoef": [
                1.8
            ],
            "defenceCoef": [],
            "info": [
                "높은 구조물 위에서 공격합니다."
            ],
            "initSkillTrigger": [
                "che_성벽부상무효"
            ],
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1501,
            "armType": 5,
            "name": "충차",
            "attack": 150,
            "defence": 100,
            "speed": 6,
            "avoid": 0,
            "magicCoef": 0,
            "cost": 10,
            "rice": 3,
            "requirements": [
                {
                    "type": "ReqTech",
                    "tech": 1000
                },
                {
                    "type": "ReqMinRelYear",
                    "year": 3
                }
            ],
            "attackCoef": [
                2.4
            ],
            "defenceCoef": [],
            "info": [
                "엄청난 위력으로 성벽을 부수어버립니다."
            ],
            "initSkillTrigger": [
                "che_성벽부상무효"
            ],
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1502,
            "armType": 5,
            "name": "벽력거",
            "attack": 200,
            "defence": 100,
            "speed": 6,
            "avoid": 0,
            "magicCoef": 0,
            "cost": 20,
            "rice": 4,
            "requirements": [
                {
                    "type": "ReqTech",
                    "tech": 3000
                },
                {
                    "type": "ReqCities",
                    "cities": [
                        "업"
                    ]
                }
            ],
            "attackCoef": [
                1.8
            ],
            "defenceCoef": [],
            "info": [
                "상대에게 돌덩이를 날립니다."
            ],
            "initSkillTrigger": [
                "che_성벽부상무효"
            ],
            "phaseSkillTrigger": null,
            "iActionList": null
        },
        {
            "id": 1503,
            "armType": 5,
            "name": "목우",
            "attack": 50,
            "defence": 200,
            "speed": 5,
            "avoid": 0,
            "magicCoef": 0,
            "cost": 15,
            "rice": 3,
            "requirements": [
                {
                    "type": "ReqTech",
                    "tech": 3000
                },
                {
                    "type": "ReqCities",
                    "cities": [
                        "성도"
                    ]
                }
            ],
            "attackCoef": [],
            "defenceCoef": [],
            "info": [
                "상대를 저지하는 특수병기입니다."
            ],
            "initSkillTrigger": [
                "che_성벽부상무효"
            ],
            "phaseSkillTrigger": null,
            "iActionList": null
        }
    ]
}
